/**
 * Données des verbes irréguliers anglais pour le jeu Speed Verb Challenge
 * Format: "infinitif": ["passé simple", "participe passé", "traduction"]
 */
window.verbData = {
    "abide": ["abode", "abode", "respecter"],
    "arise": ["arose", "arisen", "survenir"],
    "awake": ["awoke", "awoken", "s'éveiller"],
    "backbite": ["backbit", "backbitten", "médire"],
    "backslide": ["backslid", "backslidden", "rechuter"],
    "be": ["was/were", "been", "être"],
    "bear": ["bore", "borne", "porter/supporter"],
    "beat": ["beat", "beaten", "battre"],
    "become": ["became", "become", "devenir"],
    "befall": ["befell", "befallen", "arriver à"],
    "beget": ["begot", "begotten", "engendrer"],
    "begin": ["began", "begun", "commencer"],
    "behold": ["beheld", "beheld", "contempler"],
    "bend": ["bent", "bent", "plier"],
    "bereave": ["bereaved/bereft", "bereaved/bereft", "priver"],
    "beseech": ["besought/beseeched", "besought/beseeched", "supplier"],
    "beset": ["beset", "beset", "assaillir"],
    "bet": ["bet", "bet", "parier"],
    "bid": ["bid/bade", "bid/bidden", "offrir/ordonner"],
    "bind": ["bound", "bound", "lier"],
    "bite": ["bit", "bitten", "mordre"],
    "bleed": ["bled", "bled", "saigner"],
    "bless": ["blessed/blest", "blessed/blest", "bénir"],
    "blow": ["blew", "blown", "souffler"],
    "break": ["broke", "broken", "casser"],
    "breed": ["bred", "bred", "élever"],
    "bring": ["brought", "brought", "apporter"],
    "broadcast": ["broadcast", "broadcast", "diffuser"],
    "browbeat": ["browbeat", "browbeaten", "intimider"],
    "build": ["built", "built", "construire"],
    "burn": ["burnt/burned", "burnt/burned", "brûler"],
    "burst": ["burst", "burst", "éclater"],
    "buy": ["bought", "bought", "acheter"],
    "cast": ["cast", "cast", "jeter"],
    "catch": ["caught", "caught", "attraper"],
    "chide": ["chid/chided", "chid/chided/chidden", "réprimander"],
    "choose": ["chose", "chosen", "choisir"],
    "cleave": ["cleft/cleaved/clove", "cleft/cleaved/cloven", "fendre"],
    "cling": ["clung", "clung", "s'accrocher"],
    "clothe": ["clothed/clad", "clothed/clad", "vêtir"],
    "come": ["came", "come", "venir"],
    "cost": ["cost", "cost", "coûter"],
    "creep": ["crept", "crept", "ramper"],
    "crossbreed": ["crossbred", "crossbred", "croiser"],
    "cut": ["cut", "cut", "couper"],
    "daydream": ["daydreamed/daydreamt", "daydreamed/daydreamt", "rêvasser"],
    "deal": ["dealt", "dealt", "distribuer"],
    "dig": ["dug", "dug", "creuser"],
    "disprove": ["disproved", "disproved/disproven", "réfuter"],
    "dive": ["dived/dove", "dived", "plonger"],
    "do": ["did", "done", "faire"],
    "draw": ["drew", "drawn", "dessiner"],
    "dream": ["dreamt/dreamed", "dreamt/dreamed", "rêver"],
    "drink": ["drank", "drunk", "boire"],
    "drive": ["drove", "driven", "conduire"],
    "dwell": ["dwelt/dwelled", "dwelt/dwelled", "habiter"],
    "eat": ["ate", "eaten", "manger"],
    "fall": ["fell", "fallen", "tomber"],
    "feed": ["fed", "fed", "nourrir"],
    "feel": ["felt", "felt", "ressentir"],
    "fight": ["fought", "fought", "se battre"],
    "find": ["found", "found", "trouver"],
    "flee": ["fled", "fled", "fuir"],
    "fling": ["flung", "flung", "lancer"],
    "fly": ["flew", "flown", "voler"],
    "forbear": ["forbore", "forborne", "s'abstenir"],
    "forbid": ["forbade", "forbidden", "interdire"],
    "forecast": ["forecast", "forecast", "prévoir"],
    "forego": ["forewent", "foregone", "renoncer"],
    "foresee": ["foresaw", "foreseen", "prévoir"],
    "foretell": ["foretold", "foretold", "prédire"],
    "forget": ["forgot", "forgotten", "oublier"],
    "forgive": ["forgave", "forgiven", "pardonner"],
    "forsake": ["forsook", "forsaken", "abandonner"],
    "forswear": ["forswore", "forsworn", "abjurer"],
    "freeze": ["froze", "frozen", "geler"],
    "gainsay": ["gainsaid", "gainsaid", "contredire"],
    "get": ["got", "gotten", "obtenir"],
    "gild": ["gilded/gilt", "gilded/gilt", "dorer"],
    "give": ["gave", "given", "donner"],
    "go": ["went", "gone", "aller"],
    "grind": ["ground", "ground", "moudre"],
    "grow": ["grew", "grown", "grandir"],
    "hamstring": ["hamstrung", "hamstrung", "couper les jarrets"],
    "hang": ["hung", "hung", "pendre"],
    "have": ["had", "had", "avoir"],
    "hear": ["heard", "heard", "entendre"],
    "heave": ["heaved/hove", "heaved/hove", "soulever"],
    "hew": ["hewed", "hewn/hewed", "tailler"],
    "hide": ["hid", "hidden", "cacher"],
    "hit": ["hit", "hit", "frapper"],
    "hold": ["held", "held", "tenir"],
    "hurt": ["hurt", "hurt", "blesser"],
    "inbreed": ["inbred", "inbred", "consanguin"],
    "inlay": ["inlaid", "inlaid", "incruster"],
    "input": ["input", "input", "entrer des données"],
    "interbreed": ["interbred", "interbred", "croiser"],
    "interweave": ["interwove", "interwoven", "entrelacer"],
    "keep": ["kept", "kept", "garder"],
    "kneel": ["knelt/kneeled", "knelt/kneeled", "s'agenouiller"],
    "knit": ["knit/knitted", "knit/knitted", "tricoter"],
    "know": ["knew", "known", "savoir"],
    "lade": ["laded", "laden", "charger"],
    "lay": ["laid", "laid", "poser"],
    "lead": ["led", "led", "mener"],
    "lean": ["leant/leaned", "leant/leaned", "se pencher"],
    "leap": ["leapt/leaped", "leapt/leaped", "sauter"],
    "learn": ["learnt/learned", "learnt/learned", "apprendre"],
    "leave": ["left", "left", "partir"],
    "lend": ["lent", "lent", "prêter"],
    "let": ["let", "let", "laisser"],
    "lie": ["lay", "lain", "s'allonger"],
    "light": ["lit/lighted", "lit/lighted", "allumer"],
    "lose": ["lost", "lost", "perdre"],
    "make": ["made", "made", "faire"],
    "mean": ["meant", "meant", "signifier"],
    "meet": ["met", "met", "rencontrer"],
    "miscast": ["miscast", "miscast", "mal distribuer"],
    "misdeal": ["misdealt", "misdealt", "mal distribuer"],
    "misdo": ["misdid", "misdone", "mal faire"],
    "mishear": ["misheard", "misheard", "mal entendre"],
    "mislay": ["mislaid", "mislaid", "égarer"],
    "mislead": ["misled", "misled", "induire en erreur"],
    "misread": ["misread", "misread", "mal lire"],
    "misspell": ["misspelt/misspelled", "misspelt/misspelled", "mal orthographier"],
    "misspend": ["misspent", "misspent", "gaspiller"],
    "mistake": ["mistook", "mistaken", "se tromper"],
    "misunderstand": ["misunderstood", "misunderstood", "mal comprendre"],
    "mow": ["mowed", "mown/mowed", "tondre"],
    "offset": ["offset", "offset", "compenser"],
    "outbid": ["outbid", "outbid", "surenchérir"],
    "outdo": ["outdid", "outdone", "surpasser"],
    "outfight": ["outfought", "outfought", "vaincre"],
    "outgrow": ["outgrew", "outgrown", "dépasser"],
    "output": ["output", "output", "produire"],
    "outrun": ["outran", "outrun", "distancer"],
    "outsell": ["outsold", "outsold", "vendre mieux"],
    "outshine": ["outshone", "outshone", "éclipser"],
    "overbid": ["overbid", "overbid", "surenchérir"],
    "overcome": ["overcame", "overcome", "surmonter"],
    "overdo": ["overdid", "overdone", "exagérer"],
    "overdraw": ["overdrew", "overdrawn", "dépasser"],
    "overeat": ["overate", "overeaten", "trop manger"],
    "overhang": ["overhung", "overhung", "surplomber"],
    "overhear": ["overheard", "overheard", "entendre par accident"],
    "overlay": ["overlaid", "overlaid", "recouvrir"],
    "overpay": ["overpaid", "overpaid", "surpayer"],
    "override": ["overrode", "overridden", "passer outre"],
    "overrun": ["overran", "overrun", "envahir"],
    "oversee": ["oversaw", "overseen", "superviser"],
    "overshoot": ["overshot", "overshot", "dépasser"],
    "oversleep": ["overslept", "overslept", "trop dormir"],
    "overtake": ["overtook", "overtaken", "rattraper"],
    "overthrow": ["overthrew", "overthrown", "renverser"],
    "partake": ["partook", "partaken", "participer"],
    "pay": ["paid", "paid", "payer"],
    "plead": ["pled/pleaded", "pled/pleaded", "plaider"],
    "prove": ["proved", "proven/proved", "prouver"],
    "put": ["put", "put", "mettre"],
    "quick-freeze": ["quick-froze", "quick-frozen", "surgeler"],
    "quit": ["quit/quitted", "quit/quitted", "quitter"],
    "read": ["read", "read", "lire"],
    "rebind": ["rebound", "rebound", "relier"],
    "rebuild": ["rebuilt", "rebuilt", "reconstruire"],
    "recast": ["recast", "recast", "refondre"],
    "redo": ["redid", "redone", "refaire"],
    "rehear": ["reheard", "reheard", "réentendre"],
    "remake": ["remade", "remade", "refaire"],
    "rend": ["rent", "rent", "déchirer"],
    "repay": ["repaid", "repaid", "rembourser"],
    "reset": ["reset", "reset", "réinitialiser"],
    "resell": ["resold", "resold", "revendre"],
    "resend": ["resent", "resent", "renvoyer"],
    "reset": ["reset", "reset", "réinitialiser"],
    "retake": ["retook", "retaken", "reprendre"],
    "retell": ["retold", "retold", "raconter à nouveau"],
    "rethink": ["rethought", "rethought", "repenser"],
    "rewrite": ["rewrote", "rewritten", "réécrire"],
    "rid": ["rid", "rid", "débarrasser"],
    "ride": ["rode", "ridden", "monter"],
    "ring": ["rang", "rung", "sonner"],
    "rise": ["rose", "risen", "se lever"],
    "run": ["ran", "run", "courir"],
    "saw": ["sawed", "sawn/sawed", "scier"],
    "say": ["said", "said", "dire"],
    "see": ["saw", "seen", "voir"],
    "seek": ["sought", "sought", "chercher"],
    "sell": ["sold", "sold", "vendre"],
    "send": ["sent", "sent", "envoyer"],
    "set": ["set", "set", "mettre"],
    "sew": ["sewed", "sewn/sewed", "coudre"],
    "shake": ["shook", "shaken", "secouer"],
    "shave": ["shaved", "shaved/shaven", "raser"],
    "shear": ["sheared", "sheared/shorn", "tondre"],
    "shed": ["shed", "shed", "verser"],
    "shine": ["shone", "shone", "briller"],
    "shoe": ["shod", "shod", "ferrer"],
    "shoot": ["shot", "shot", "tirer"],
    "show": ["showed", "shown/showed", "montrer"],
    "shrink": ["shrank/shrunk", "shrunk", "rétrécir"],
    "shut": ["shut", "shut", "fermer"],
    "sing": ["sang", "sung", "chanter"],
    "sink": ["sank", "sunk", "couler"],
    "sit": ["sat", "sat", "s'asseoir"],
    "slay": ["slew", "slain", "tuer"],
    "sleep": ["slept", "slept", "dormir"],
    "slide": ["slid", "slid", "glisser"],
    "sling": ["slung", "slung", "lancer"],
    "slink": ["slunk", "slunk", "se faufiler"],
    "slit": ["slit", "slit", "fendre"],
    "smell": ["smelt/smelled", "smelt/smelled", "sentir"],
    "smite": ["smote", "smitten", "frapper"],
    "sow": ["sowed", "sown/sowed", "semer"],
    "speak": ["spoke", "spoken", "parler"],
    "speed": ["sped/speeded", "sped/speeded", "accélérer"],
    "spell": ["spelt/spelled", "spelt/spelled", "épeler"],
    "spend": ["spent", "spent", "dépenser"],
    "spill": ["spilt/spilled", "spilt/spilled", "renverser"],
    "spin": ["spun", "spun", "tourner"],
    "spit": ["spat", "spat", "cracher"],
    "split": ["split", "split", "diviser"],
    "spoil": ["spoilt/spoiled", "spoilt/spoiled", "gâcher"],
    "spread": ["spread", "spread", "répandre"],
    "spring": ["sprang", "sprung", "sauter"],
    "stand": ["stood", "stood", "se tenir debout"],
    "stave": ["staved/stove", "staved/stove", "défoncer"],
    "steal": ["stole", "stolen", "voler"],
    "stick": ["stuck", "stuck", "coller"],
    "sting": ["stung", "stung", "piquer"],
    "stink": ["stank/stunk", "stunk", "puer"],
    "strew": ["strewed", "strewn/strewed", "éparpiller"],
    "stride": ["strode", "stridden", "marcher à grands pas"],
    "strike": ["struck", "struck/stricken", "frapper"],
    "string": ["strung", "strung", "enfiler"],
    "strive": ["strove", "striven", "s'efforcer"],
    "sublet": ["sublet", "sublet", "sous-louer"],
    "swear": ["swore", "sworn", "jurer"],
    "sweep": ["swept", "swept", "balayer"],
    "swell": ["swelled", "swollen/swelled", "gonfler"],
    "swim": ["swam", "swum", "nager"],
    "swing": ["swung", "swung", "balancer"],
    "take": ["took", "taken", "prendre"],
    "teach": ["taught", "taught", "enseigner"],
    "tear": ["tore", "torn", "déchirer"],
    "tell": ["told", "told", "dire"],
    "think": ["thought", "thought", "penser"],
    "thrive": ["throve/thrived", "thriven/thrived", "prospérer"],
    "throw": ["threw", "thrown", "jeter"],
    "thrust": ["thrust", "thrust", "pousser"],
    "tread": ["trod", "trodden/trod", "fouler"],
    "unbend": ["unbent", "unbent", "redresser"],
    "unbind": ["unbound", "unbound", "délier"],
    "underbid": ["underbid", "underbid", "sous-enchérir"],
    "undergo": ["underwent", "undergone", "subir"],
    "understand": ["understood", "understood", "comprendre"],
    "undertake": ["undertook", "undertaken", "entreprendre"],
    "underwrite": ["underwrote", "underwritten", "souscrire"],
    "undo": ["undid", "undone", "défaire"],
    "unfreeze": ["unfroze", "unfrozen", "dégeler"],
    "unhang": ["unhung", "unhung", "décrocher"],
    "unhide": ["unhid", "unhidden", "révéler"],
    "unlearn": ["unlearnt/unlearned", "unlearnt/unlearned", "désapprendre"],
    "unsay": ["unsaid", "unsaid", "rétracter"],
    "unwind": ["unwound", "unwound", "dérouler"],
    "uphold": ["upheld", "upheld", "soutenir"],
    "upset": ["upset", "upset", "contrarier"],
    "wake": ["woke", "woken", "se réveiller"],
    "waylay": ["waylaid", "waylaid", "guetter"],
    "wear": ["wore", "worn", "porter"],
    "weave": ["wove", "woven", "tisser"],
    "wed": ["wed/wedded", "wed/wedded", "épouser"],
    "weep": ["wept", "wept", "pleurer"],
    "wet": ["wet/wetted", "wet/wetted", "mouiller"],
    "win": ["won", "won", "gagner"],
    "wind": ["wound", "wound", "enrouler"],
    "withdraw": ["withdrew", "withdrawn", "retirer"],
    "withhold": ["withheld", "withheld", "retenir"],
    "withstand": ["withstood", "withstood", "résister"],
    "wring": ["wrung", "wrung", "tordre"],
    "write": ["wrote", "written", "écrire"]
};
